import jannchie from '@jannchie/eslint-config'

export default jannchie(
  {
    react: false,
    typescript: {
      tsconfigPath: 'tsconfig.json',
    },
    ignores: [
      'logs',
      '*.log',
      'pids',
      '*.pid',
      '*.seed',
      'coverage',
      '.eslintcache',
      'node_modules',
      '.DS_Store',
      '.erb/**',
      '.vscode/**',
      'assets/**',
      'dist/**',
      'public/**',
      'release/app/dist',
      'release/build',
      'release/**',
      'eslint.config.mjs',
      'postcss.config.js',
      'tailwind.config.js',
      'vite.config.mts',
      '**/*.config.{js,cjs,mjs,ts}',
      '**/*.d.ts',
      '.idea',
      'npm-debug.log.*',
      '*.css.d.ts',
      '*.sass.d.ts',
      '*.scss.d.ts',
      'lint.json',
      '*.ejs',
    ],
  },
  {
    name: 'active-time/style-overrides',
    rules: {
      'style/semi': 'off',
      'style/arrow-parens': 'off',
      'style/array-element-newline': 'off',
      'style/brace-style': 'off',
      'style/comma-dangle': 'off',
      'style/member-delimiter-style': 'off',
      'style/operator-linebreak': 'off',
      'style/quote-props': 'off',
      'prefer-const': 'off',
      'eslint-comments/no-unlimited-disable': 'off',
      'unicorn/explicit-length-check': 'off',
      'unicorn/catch-error-name': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'unicorn/no-negated-condition': 'off',
      'unicorn/no-array-for-each': 'off',
      'unicorn/no-array-sort': 'off',
      'unicorn/no-await-expression-member': 'off',
      'unicorn/no-static-only-class': 'off',
      'unicorn/no-useless-undefined': 'off',
      'unicorn/numeric-separators-style': 'off',
      'unicorn/number-literal-case': 'off',
      'unicorn/prefer-code-point': 'off',
      'unicorn/prefer-date-now': 'off',
      'unicorn/prefer-export-from': 'off',
      'unicorn/prefer-global-this': 'off',
      'unicorn/prefer-module': 'off',
      'unicorn/prefer-native-coercion-functions': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/prefer-spread': 'off',
      'unicorn/prefer-string-raw': 'off',
      'unicorn/prefer-top-level-await': 'off',
      'unicorn/prefer-switch': 'off',
      'unicorn/require-module-specifiers': 'off',
      'unicorn/switch-case-braces': 'off',
      'regexp/no-super-linear-backtracking': 'off',
      'regexp/no-unused-capturing-group': 'off',
      'node/prefer-global/buffer': 'off',
      'antfu/top-level-function': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-named-imports': 'off',
      'perfectionist/sort-named-exports': 'off',
      'ts/consistent-type-definitions': 'off',
      'ts/consistent-type-imports': 'off',
      'ts/method-signature-style': 'off',
      'ts/no-misused-promises': 'off',
      'ts/no-unsafe-return': 'off',
      'ts/no-use-before-define': 'off',
      'ts/no-floating-promises': 'off',
      'ts/no-require-imports': 'off',
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/promise-function-async': 'off',
      'ts/strict-boolean-expressions': 'off',
      'ts/switch-exhaustiveness-check': 'off',
      'vue/block-order': 'off',
      'vue/singleline-html-element-content-newline': 'off',
    },
  },
  {
    name: 'active-time/json-overrides',
    files: ['**/*.{json,jsonc,json5}'],
    rules: {
      'jsonc/comma-dangle': 'off',
      'jsonc/sort-keys': 'off',
    },
  },
  {
    name: 'active-time/test-overrides',
    files: ['**/__tests__/**/*.{ts,tsx,js,jsx}'],
    rules: {
      'test/prefer-lowercase-title': 'off',
    },
  },
  {
    name: 'active-time/overrides',
    files: ['**/*.{ts,tsx}'],
    rules: {
      'ts/no-explicit-any': 'off',
    },
  }
)
