/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDashboardGroup: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDashboardSidebarToggle: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UProgress: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.3.0_67acc995d7fd6e1db1b27575338ae027/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
  }
}
